Table AuthSession {
  token uuid pk [default: `uuid()`]
  userUid uuid pk [ref: > User.id]

  agent string

  createdAt datetime [default: `now()`]
  expiresAt datetime
  revokedAt datetime [null, default: null]
}