Enum Role {
  admin
  moderator
  accountant
  writer
  support
  member
}
Table User {
  id uuid pk [default: `cuid()`]

  firstname string
  lastname string
  roles Role[] [default: "[member]"]

  email string unique
  password string [null]

  createdAt datetime [default: `now()`]
  updatedAt datetime [default: `now()`]
}